CREATE SCHEMA JORDAN;

;

SELECT *
FROM EXPENDITURE
LIMIT 10

;

-- 1) Number of Transactions
SELECT COUNT(DISTINCT TRANSACTION_NUMBER) AS Number_Of_Transactions
FROM EXPENDITURE;
-- Unsure if the dates in Transaction Number column skews this number. 


-- 2) Average Yearly Spend
SELECT ROUND(AVG(t.Yearly_Spend),2) AS Average_Yearly_Spend
FROM (SELECT date_part(YEAR, DATE) AS Year, SUM(EXPENDITURE) AS Yearly_Spend
FROM EXPENDITURE
GROUP BY date_part(YEAR, DATE))t;

-- 3) Top 3 supplier by Spend
SELECT SUPPLIER, ROUND(SUM(EXPENDITURE),2) AS Total_Spend
FROM EXPENDITURE
GROUP BY SUPPLIER
ORDER BY SUM(EXPENDITURE) DESC
LIMIT 3

-- 4)
SELECT EXPENSE_AREA, SUM(EXPENDITURE) AS Total_Spend
FROM EXPENDITURE
GROUP BY EXPENSE_AREA
ORDER BY SUM(EXPENDITURE) DESC
LIMIT 1

-- 5)
SELECT COUNT(DISTINCT SUPPLIER) AS Number_Of_Suppliers
FROM EXPENDITURE;
